# Gen Z Slang to Formal Language Dictionary
translation_dict_z_to_f = {
    "sup": "hi",
    "lit": "good",
    "fire": "cool",
    "slay": "excel",
    "vibe": "mood",
    "fam": "family",
    "homie": "friend",
    "bet": "yes",
    "sus": "suspicious",
    "stan": "support",
    "mood": "feeling",
    "savage": "bold",
    "ghost": "ignore",
    "clapback": "retort",
    "cringe": "awkward",
    "shade": "disrespect",
    "woke": "socially aware",
    "finesse": "succeed",
    "lowkey": "secretly",
    "highkey": "obviously",
    "no cap": "no lie",
    "litty": "super fun",
    "extra": "over the top",
    "flex": "show off",
    "slaps": "good music",
    "drip": "fashion",
    "YOLO": "you only live once",
    "shook": "shocked",
    "bop": "good song",
    "tea": "gossip",
    "thirsty": "desperate",
    "bruh": "dude",
    "tbh": "to be honest",
    "L": "loss",
    "W": "win",
    "no worries": "it's fine",
    "BFF": "best friend forever",
    "catching hands": "fighting",
    "meme": "funny image or video",
    "swag": "confidence",
    "on point": "perfect",
    "wasted": "drunk",
    "turnt": "excited",
    "yo": "hello",
    "wassup": "what's up",
    "a force": "unnecessarily excessive effort",
    "bang 30s": "to fight someone",
    "beat your face/cake your face": "apply makeup",
    "bops": "a modern enjoyable song",
    "bouta": "I am about to...",
    "bread": "future money",
    "catch a fade/catch these hands": "to get punched",
    "clap back": "respond to an insult with equal or greater insult",
    "clapped": "a crazy person",
    "crackie": "someone who juuls/smokes",
    "cross fade": "doubly inebriated",
    "deadass": "I am serious",
    "dead dogs/on dogs": "seriously",
    "don’t do me dirty": "don’t cross me",
    "extra": "too much",
    "facts": "I agree with what you said",
    "finesse": "to steal",
    "finna": "I am about to",
    "flexed on": "a verbal gesture of dominance",
    "the game life": "life",
    "gassing/hyping": "offering compliments",
    "gotta blast": "I have to leave",
    "hardo": "a try-hard",
    "high key": "very obvious",
    "hip/get hip": "adopt a new trend",
    "hop off": "mind your business",
    "i’m dead": "that was amusing",
    "jams": "old enjoyable song",
    "jawn": "thing, object, person, place",
    "low key": "not obvious",
    "mad mad/big mad": "very mad",
    "nunya": "none of your business",
    "on blast": "expose someone",
    "opp": "snitch or enemy",
    "periodt": "for sure",
    "pull up/come thru": "an invitation",
    "put someone on": "getting someone on a trend",
    "rashing": "to make fun of someone",
    "real one": "a trusted person",
    "run that...": "to take",
    "secure(d) the bag": "money received",
    "shlitty": "a good time",
    "sis": "universal nickname for a friend",
    "slaps": "high quality",
    "slay": "do really well",
    "smacks": "tasty treat",
    "snack": "attractive person",
    "stay up": "you’ll be ok",
    "sus": "suspicious",
    "take the L": "sacrifice",
    "tea/spill the tea": "gossip",
    "that ain’t it": "unacceptable",
    "tight": "extremely mad",
    "tryna": "trying to",
    "tweakin": "overreacting",
    "valid": "of high quality",
    "we love that": "ironic response",
    "wig snatched": "impressive act",
    "witchu": "with you",
    "yahurrd": "are you aware?",
    "you got jokes/big jokes": "sarcastic response",
    "yurrr/yerrr": "affirmative",
}

# Formal Language to Gen Z Slang Dictionary
translation_dict_f_to_z = {
    "hi": "sup",
    "good": "lit",
    "cool": "fire",
    "excel": "slay",
    "mood": "vibe",
    "family": "fam",
    "friend": "homie",
    "yes": "bet",
    "suspicious": "sus",
    "support": "stan",
    "feeling": "mood",
    "bold": "savage",
    "ignore": "ghost",
    "retort": "clapback",
    "awkward": "cringe",
    "disrespect": "shade",
    "socially aware": "woke",
    "succeed": "finesse",
    "secretly": "lowkey",
    "obviously": "highkey",
    "no lie": "no cap",
    "super fun": "litty",
    "over the top": "extra",
    "show off": "flex",
    "good music": "slaps",
    "fashion": "drip",
    "you only live once": "YOLO",
    "shocked": "shook",
    "good song": "bop",
    "gossip": "tea",
    "desperate": "thirsty",
    "dude": "bruh",
    "to be honest": "tbh",
    "loss": "L",
    "win": "W",
    "it's fine": "no worries",
    "best friend forever": "BFF",
    "fighting": "catching hands",
    "funny image or video": "meme",
    "confidence": "swag",
    "perfect": "on point",
    "drunk": "wasted",
    "excited": "turnt",
    "hello": "yo",
    "what's up": "wassup",
    "unnecessarily excessive effort": "a force",
    "to fight someone": "bang 30s",
    "apply makeup": "beat your face/cake your face",
    "a modern enjoyable song": "bops",
    "I am about to...": "bouta",
    "future money": "bread",
    "to get punched": "catch a fade/catch these hands",
    "respond to an insult with equal or greater insult": "clap back",
    "a crazy person": "clapped",
    "someone who juuls/smokes": "crackie",
    "doubly inebriated": "cross fade",
    "I am serious": "deadass",
    "seriously": "dead dogs/on dogs",
    "don’t cross me": "don’t do me dirty",
    "too much": "extra",
    "I agree with what you said": "facts",
    "to steal": "finesse",
    "I or We are planning something": "finna",
    "a verbal gesture of dominance": "flexed on",
    "life": "the game life",
    "offering compliments": "gassing/hyping",
    "I have to leave": "gotta blast",
    "a try-hard": "hardo",
    "very obvious": "high key",
    "adopt a new trend": "hip/get hip",
    "mind your business": "hop off",
    "that was amusing": "i’m dead",
    "old enjoyable song": "jams",
    "thing, object, person, place": "jawn",
    "not obvious": "low key",
    "very mad": "mad mad/big mad",
    "none of your business": "nunya",
    "expose someone": "on blast",
    "snitch or enemy": "opp",
    "for sure": "periodt",
    "an invitation": "pull up/come thru",
    "getting someone on a trend": "put someone on",
    "to make fun of someone": "rashing",
    "a trusted person": "real one",
    "to take": "run that...",
    "money received": "secure(d) the bag",
    "a good time": "shlitty",
    "universal nickname for a friend": "sis",
    "high quality": "slaps",
    "do really well": "slay",
    "tasty treat": "smacks",
    "attractive person": "snack",
    "you’ll be ok": "stay up",
    "suspicious": "sus",
    "sacrifice": "take the L",
    "gossip": "tea",
    "unacceptable": "that ain’t it",
    "extremely mad": "tight",
    "trying to": "tryna",
    "overreacting": "tweakin",
    "of high quality": "valid",
    "ironic response": "we love that",
    "impressive act": "wig snatched",
    "with you": "witchu",
    "are you aware?": "yahurrd",
    "sarcastic response": "you got jokes/big jokes",
    "affirmative": "yurrr/yerrr",
    "she":"gurl",
    "he":"boi",

}

#urdu to english
translation_dict_u_to_e = {
    "yaar": "buddy",
    "yar": "buddy",
    "yr": "buddy",
    "chill scene hai" : "it's a chill scene",
    "scene": "situation",
    "easy scene": "easy situation",
    "bindaas": "cool, carefree",
    "chill maar": "relax, take it easy",
    "fazool": "useless, pointless",
    "jhakaas": "amazing, awesome",
    "patli gali se nikal": "get out of trouble",
    "lafda": "problem, issue",
    "tu kahan main kahan": "we are worlds apart",
    "mast": "cool, great",
    "bhai ka panga": "get into trouble with someone",
    "suno sunao": "gossip, talk about something",
    "zordar": "loud, impactful",
    "tension na lo": "don't stress, don't worry",
    "pehli dafa": "first time",
    "dheere dheere": "slowly, take it easy",
    "shugal": "fun, entertainment",
    "garam": "angry, intense (also spicy food)",
    "ghuma phira": "avoid the topic, beat around the bush",
    "hawa mein udaan": "extremely happy, in a very good mood",
    "billo": "cute, sweet",
    "burger": "westernized, posh",
    "chakkar": "problem, issue",
    "dheet": "stubborn, hard-headed",
    "dil pe mat lo": "don't take it to heart",
    "faltu": "useless, pointless",
    "jugaad": "hack, workaround",
    "kalti": "twist, turn",
    "lattu": "crazy, obsessed",
    "masti": "fun, enjoyment",
    "nakhre": "tantrums, drama",
    "panga": "trouble, conflict",
    "senti": "sentimental, emotional",
    "shona": "sweetheart, darling",
    "sutta": "cigarette",
    "tashan": "style, attitude",
    "timepass": "killing time",
    "vella": "idle, lazy",
    "zindagi": "life",
    "bhai": "brother",
    "bhabhi": "brother's wife",
    "chacha": "uncle",
    "chachi": "aunt",
    "dada": "paternal grandfather",
    "dadi": "paternal grandmother",
    "mama": "maternal uncle",
    "kalu": "dark-skinned person",
    "golu": "chubby person",
    "motu": "fat person",
    "chotu": "short person",
    "lallu": "foolish person",
    "bholu": "innocent person",
    "chamak challo": "  attractive ",
    "paindu": "villager",
}




